"""initial schema

Revision ID: 21978d20b83a
Revises: 
Create Date: 2026-08-12 21:17:20.958017

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21978d20b83a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('iso3', sa.String(length=3), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('name_fr', sa.Text(), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('in_analog_pool', sa.Boolean(), nullable=False),
    sa.Column('currency_hist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('iso3')
    )
    op.create_table('indicators',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label_fr', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.Column('family', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('is_derived', sa.Boolean(), nullable=False),
    sa.Column('derivation', sa.Text(), nullable=True),
    sa.Column('higher_is_worse', sa.Boolean(), nullable=True),
    sa.Column('definition_fr', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('sources',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('citation', sa.Text(), nullable=False),
    sa.Column('licence', sa.Text(), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('retrieved_at', sa.Date(), nullable=False),
    sa.Column('file_sha256', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state_vectors',
    sa.Column('country_iso3', sa.String(length=3), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('feature_code', sa.Text(), nullable=False),
    sa.Column('build_id', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Double(), nullable=True),
    sa.Column('pct_rank', sa.Double(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('country_iso3', 'year', 'feature_code', 'build_id')
    )
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('country_iso3', sa.String(length=3), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('label_fr', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.Column('severity', sa.SmallInteger(), nullable=True),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('notes_fr', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['country_iso3'], ['countries.iso3'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_country_date', 'events', ['country_iso3', 'date_start'], unique=False)
    op.create_table('raw_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('vintage', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('relpath', sa.Text(), nullable=False),
    sa.Column('media_type', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('origin_url', sa.Text(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archive_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('observations',
    sa.Column('country_iso3', sa.String(length=3), nullable=False),
    sa.Column('indicator_code', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('freq', sa.String(length=1), nullable=False),
    sa.Column('value', sa.Double(), nullable=True),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('is_interpolated', sa.Boolean(), nullable=False),
    sa.Column('is_spliced', sa.Boolean(), nullable=False),
    sa.Column('is_break', sa.Boolean(), nullable=False),
    sa.Column('conflict', sa.Boolean(), nullable=False),
    sa.Column('coverage_partial', sa.Boolean(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_file_id', sa.BigInteger(), nullable=True),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_value_text', sa.Text(), nullable=True),
    sa.Column('transform_chain', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['country_iso3'], ['countries.iso3'], ),
    sa.ForeignKeyConstraint(['indicator_code'], ['indicators.code'], ),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_files.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('country_iso3', 'indicator_code', 'period_start', 'freq')
    )
    op.create_index('ix_observations_country_period', 'observations', ['country_iso3', 'period_start'], unique=False)
    op.create_index('ix_observations_indicator_period', 'observations', ['indicator_code', 'period_start'], unique=False)
    op.create_table('observations_alt',
    sa.Column('country_iso3', sa.String(length=3), nullable=False),
    sa.Column('indicator_code', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('freq', sa.String(length=1), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('value', sa.Double(), nullable=True),
    sa.Column('is_interpolated', sa.Boolean(), nullable=False),
    sa.Column('is_spliced', sa.Boolean(), nullable=False),
    sa.Column('is_break', sa.Boolean(), nullable=False),
    sa.Column('conflict', sa.Boolean(), nullable=False),
    sa.Column('coverage_partial', sa.Boolean(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_file_id', sa.BigInteger(), nullable=True),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_value_text', sa.Text(), nullable=True),
    sa.Column('transform_chain', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['country_iso3'], ['countries.iso3'], ),
    sa.ForeignKeyConstraint(['indicator_code'], ['indicators.code'], ),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_files.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('country_iso3', 'indicator_code', 'period_start', 'freq', 'source_id')
    )
    op.create_table('source_pages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('raw_file_id', sa.BigInteger(), nullable=False),
    sa.Column('page_number', sa.SmallInteger(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('image_sha256', sa.Text(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('rendered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_file_id', 'page_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_pages')
    op.drop_table('observations_alt')
    op.drop_index('ix_observations_indicator_period', table_name='observations')
    op.drop_index('ix_observations_country_period', table_name='observations')
    op.drop_table('observations')
    op.drop_table('raw_files')
    op.drop_index('ix_events_country_date', table_name='events')
    op.drop_table('events')
    op.drop_table('state_vectors')
    op.drop_table('sources')
    op.drop_table('indicators')
    op.drop_table('countries')
    # ### end Alembic commands ###
