"""page_views table for admin analytics

Revision ID: fc77db09a6e1
Revises: 0cc3ae70399f
Create Date: 2026-09-30 07:39:31.860219

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc77db09a6e1'
down_revision: str | None = '0cc3ae70399f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_views',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_page_views_viewed_at', 'page_views', ['viewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_page_views_viewed_at', table_name='page_views')
    op.drop_table('page_views')
    # ### end Alembic commands ###
